Port to bun.sh (#419)
* fix embershots

* initial conversion

* update dependencies

* fix github actions

* remove vite favicon plugin (as it breaks shit for now)

* use bun x instead of bunx

* remove unnecessary parameter

* disable TSC for now

* add custom™ benchmark tool

* update deploy script to use/install bun

* remove engines definition to trick netlify into deploying this maybe

* re-add vite-plugin-favicon

* remove node/jest specific configs

* fix tsc problems

* make json linter happy

diff --git a/scripts/json-linter b/scripts/json-linter
--- a/scripts/json-linter
+++ b/scripts/json-linter
@@ -4,5 +4,11 @@ if [[ -z $(command -v python) ]]; then
   exit 1
 fi
 
-python -m pip install json-linter -U > /dev/null
-python -m json_linter ${@}
+if [[ -z $(command -v pipx) ]]; then
+  echo "ERR: pipx is required!"
+  echo "Install via: pip install pipx"
+  exit 1
+fi
+
+python -m pipx install json-linter -U > /dev/null
+pipx run json-linter ${@}
